lib/helheim_web/router.ex
defmodule HelheimWeb.Router do
  use HelheimWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HelheimWeb.Locale
  end

  pipeline :auth do
    plug HelheimWeb.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug HelheimWeb.Plug.TrackLogin
    plug HelheimWeb.Plug.LoadNotifications
    plug HelheimWeb.Plug.LoadUnreadPrivateConversations
    plug HelheimWeb.Plug.LoadPendingFriendships
    plug HelheimWeb.Plug.EnforceBan
    plug HelheimWeb.Plug.LoadPendingCalendarEvents
    plug HelheimWeb.Plug.LoadIgnorees
  end

  pipeline :ensure_admin do
    plug HelheimWeb.Plug.VerifyAdmin
  end

  pipeline :ensure_mod do
    plug HelheimWeb.Plug.VerifyMod
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser] # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/confirmation_pending", PageController, :confirmation_pending
    get "/debug", PageController, :debug
    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/confirmations", ConfirmationController, only: [:new, :create, :show]
    resources "/password_resets", PasswordResetController, only: [:new, :create, :show, :update]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/banned", PageController, :banned
    get "/help/verification", HelpController, :verification
    get "/signed_in", PageController, :signed_in
    get "/front_page", PageController, :front_page
    get "/staff", PageController, :staff
    get "/sessions/sign_out", SessionController, :delete
    resources "/account", AccountController, singleton: true, only: [:edit, :update, :delete]
    resources "/preferences", PreferenceController, singleton: true, only: [:edit, :update]
    resources "/profile", ProfileController, singleton: true, only: [:show, :edit, :update]
    resources "/profiles", ProfileController, only: [:index, :show], as: :public_profile do
      resources "/blog_posts", BlogPostController, only: [:index, :show] do
        resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      end
      resources "/comments", CommentController, only: [:index, :create, :edit, :update]
      resources "/photo_albums", PhotoAlbumController, only: [:index, :show] do
        resources "/photos", PhotoController, only: [:show] do
          resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
        end
        resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      end
      resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
      resources "/contact_request", FriendshipRequestController, singleton: true, only: [:create, :delete]
      resources "/contact", FriendshipController, singleton: true, only: [:create, :delete]
      resources "/contacts", FriendshipController, only: [:index]
    end
    resources "/blog_posts", BlogPostController, only: [:index, :new, :create, :edit, :update, :delete] do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/photo_albums", PhotoAlbumController, only: [:new, :create, :edit, :update, :delete] do
      resources "/photos", PhotoController, only: [:create, :edit, :update, :delete] do
        resources "/comments", CommentController, only: [:create, :edit, :update]
        resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
      end
      resources "/photo_positions", PhotoPositionController, singleton: true, only: [:update], as: :photo_positions
    end
    resources "/photos", PhotoController, only: [:index]
    resources "/private_conversations", PrivateConversationController, param: "partner_id", only: [:index, :show, :delete] do
      resources "/messages", PrivateMessageController, only: [:create], as: :message
    end
    resources "/forums", ForumController, only: [:index, :show] do
      resources "/forum_topics", ForumTopicController, only: [:new, :create, :show, :edit, :update] do
        resources "/forum_replies", ForumReplyController, only: [:create, :edit, :update]
      end
    end
    resources "/forum_topics", ForumTopicController, only: [] do
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/notifications", NotificationController, only: [:show]
    resources "/navbar", NavbarController, singleton: true, only: [:show]
    resources "/usernames", UsernameController, only: [:index, :show]
    resources "/blocks_and_ignores", BlockAndIgnoreController, only: [:index]
    resources "/blocks", BlockController, except: [:index]
    resources "/ignores", IgnoreController, except: [:index, :show]
    resources "/comments", CommentController, only: [:delete]
    resources "/donations", DonationController, only: [:new, :create]
    get "/donations/thank_you", DonationController, :thank_you
    resources "/contacts", FriendshipController, only: [:index]
    resources "/calendar_events", CalendarEventController do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/online_users", OnlineUserController, only: [:index]
  end

  scope "/mod", HelheimWeb.Mod, as: :mod do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_mod]

    resources "/calendar_events", CalendarEventController, only: [:index, :show, :update, :delete]
  end

  scope "/admin", HelheimWeb.Admin, as: :admin do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_admin]

    live_dashboard "/dashboard", metrics: HelheimWeb.Telemetry

    resources "/forum_categories", ForumCategoryController, only: [:index, :new, :create, :edit, :update, :delete] do
      resources "/forums", ForumController, only: [:new, :create, :edit, :update, :delete]
    end
    resources "/terms", TermController
    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      resources "/verification", User.VerificationController, singleton: true, only: [:create, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Helheim do
  #   pipe_through :api
  # end

  if Application.fetch_env!(:helheim, :env) == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/helheim/models/block.ex
defmodule Helheim.Block do
  use Helheim, :model

  alias Helheim.Block
  alias Helheim.Repo
  alias Helheim.User

  schema "blocks" do
    belongs_to :blocker, User
    belongs_to :blockee, User
    field      :enabled, :boolean
    timestamps(type: :utc_datetime_usec)
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:enabled])
  end

  def for_blocker(query, blocker) do
    from b in query, where: b.blocker_id == ^blocker.id
  end

  def for_blockee(query, blockee) do
    from b in query, where: b.blockee_id == ^blockee.id
  end

  def involving_user(query, user) do
    from b in query, where: b.blocker_id == ^user.id or b.blockee_id == ^user.id
  end

  def order_by_blocker_and_blockee_username(query) do
    from b in query,
      join: blocker in User, on: blocker.id == b.blocker_id,
      join: blockee in User, on: blockee.id == b.blockee_id,
      order_by: [blocker.username, blockee.username]
  end

  def order_by_blockee_username(query) do
    from b in query,
      join: u in User, on: u.id == b.blockee_id,
      order_by: u.username
  end

  def enabled(query) do
    from b in query, where: b.enabled == true
  end

  def blocked?(blocker_id, blockee) when is_integer(blocker_id) do
    Repo.get!(User, blocker_id)
    |> blocked?(blockee)
  end
  def blocked?(%User{} = blocker, blockee) do
    block = Block
            |> Block.for_blocker(blocker)
            |> Block.for_blockee(blockee)
            |> Block.enabled()
            |> Repo.one
    case block do
      nil -> false
        _ -> true
    end
  end

  def block!(%{id: blocker_id}, %{id: blockee_id}) when blocker_id == blockee_id, do: {:error, "Blocker and blockee must be different!"}
  def block!(blocker, blockee) do
    Block.changeset(existing_block(blocker, blockee) || new_block(blocker, blockee))
    |> Ecto.Changeset.put_change(:enabled, true)
    |> Repo.insert_or_update
  end

  def unblock!(%{id: blocker_id}, %{id: blockee_id}) when blocker_id == blockee_id, do: {:error, "Blocker and blockee must be different!"}
  def unblock!(blocker, blockee) do
    Ecto.Changeset.change(existing_block(blocker, blockee) || new_block(blocker, blockee))
    |> Ecto.Changeset.put_change(:enabled, false)
    |> Repo.insert_or_update
  end

  defp existing_block(blocker, blockee) do
    Block
    |> Block.for_blocker(blocker)
    |> Block.for_blockee(blockee)
    |> Repo.one
  end

  defp new_block(blocker, blockee) do
    Block.changeset(%Block{}, %{})
    |> Ecto.Changeset.put_assoc(:blocker, blocker)
    |> Ecto.Changeset.put_assoc(:blockee, blockee)
  end
end

lib/helheim_web/controllers/block_controller.ex
defmodule HelheimWeb.BlockController do
  use HelheimWeb, :controller
  alias Helheim.Block
  alias Helheim.User

  def index(conn, params) do
    user   = current_resource(conn)
    blocks = Block
             |> Block.for_blocker(user)
             |> Block.enabled()
             |> Block.order_by_blockee_username()
             |> preload(:blockee)
             |> Repo.paginate(page: sanitized_page(params["page"]))
    render(conn, "index.html", blocks: blocks)
  end

  def show(conn, %{"id" => blocker_id}) do
    blocker = Repo.get!(User, blocker_id)
    blockee = current_resource(conn)
    block   = Block
              |> Block.for_blocker(blocker)
              |> Block.for_blockee(blockee)
              |> Block.enabled()
              |> Repo.one!
    render(conn, "show.html", block: block, blocker: blocker)
  end

  def new(conn, _params) do
    blocker   = current_resource(conn)
    users     = User
                |> User.blockable_by(blocker)
                |> User.sort("username", "asc")
                |> Repo.all
    render(conn, "new.html", users: users)
  end

  def create(conn, %{"blockee_id" => blockee_id}) do
    with blocker <- current_resource(conn),
      {:ok, blockee} <- find_blockee(blocker, blockee_id),
      {:ok, _block} <- Block.block!(blocker, blockee)
    do
      conn
      |> put_flash(:success, gettext("User successfully blocked!"))
      |> redirect(to: block_and_ignore_path(conn, :index))
    else
      _ ->
        conn
        |> put_flash(:error, gettext("Unable to block user!"))
        |> redirect(to: block_and_ignore_path(conn, :index))
    end
  end

  def delete(conn, %{"id" => blockee_id}) do
    blocker = current_resource(conn)
    blockee = Repo.get!(User, blockee_id)

    case Block.unblock!(blocker, blockee) do
      {:ok, _block} ->
        conn
        |> put_flash(:success, gettext("User unblocked!"))
        |> redirect(to: block_and_ignore_path(conn, :index))
      {:error, _} ->
        conn
        |> put_flash(:error, gettext("Unable to unblock user!"))
        |> redirect(to: block_and_ignore_path(conn, :index))
    end
  end

  defp find_blockee(blocker, blockee_id) do
    blockee = User |> User.blockable_by(blocker) |> Repo.get(blockee_id)
    if blockee do
      {:ok, blockee}
    else
      {:error, :blockee_not_found}
    end
  end
end

lib/helheim_web/views/block_view.ex
defmodule HelheimWeb.BlockView do
  use HelheimWeb, :view
end

lib/helheim_web/templates/block/form.html.eex
<%= form_for @conn, @action, fn f -> %>
  <div class="card-block">
    <p class="mb-2">
      <i class="fa fa-info-circle"></i>
      <%= gettext "The user will be unable to see your profile, blog posts, photos or send you messages while blocked" %>
    </p>
    <div class="form-group <%= if f.errors[:blockee_id] do 'has-danger' end %>">
      <%= label f, :blockee_id, gettext("Who?"), class: "control-label" %>
      <%= select f, :blockee_id, Enum.map(@users, &[key: &1.username, value: &1.id]), prompt: [key: '', value: nil], class: "form-control" %>
      <%= if message = f.errors[:blockee_id] do %>
        <div class="form-control-feedback"><%= translate_error(message) %></div>
      <% end %>
    </div>
  </div>
  <div class="card-footer">
    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> <%= gettext "Block user" %></button>
  </div>
<% end %>

lib/helheim_web/templates/block/index.html.eex
<ol class="breadcrumb">
  <li class="breadcrumb-item active"><%= gettext("Blocks") %></li>
</ol>

<div class="card card-dark">
  <div class="card-block">
    <h4 class="card-title"><%= gettext "These are the users that you have blocked" %>:</h4>
    <p class="mb-2">
      <i class="fa fa-info-circle"></i>
      <%= gettext "The user will be unable to see your profile, blog posts, photos or send you messages while blocked" %>
    </p>
    <table class="table">
      <tbody>
        <%= for block <- @blocks.entries do %>
          <tr>
            <td>
              <strong>
                <%= link block.blockee.username, to: public_profile_path(@conn, :show, block.blockee) %><br>
              </strong>
              <small>
                <%= gettext "Blocked since:" %>
                <%= lt(block.updated_at, "%d. %b %Y kl. %H:%M") %>
              </small>
            </td>
            <td class="text-right">
              <%= link to: block_path(@conn, :delete, block.blockee_id), method: "DELETE" do %>
                <i class="fa fa-trash" title="<%= gettext "Unblock user" %>"></i>
                <span class="hidden-xs-down"><%= gettext "Unblock user" %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link to: block_path(@conn, :new), class: "btn btn-primary btn-sm" do %>
      <i class="fa fa-plus"></i>
      <%= gettext("Create block") %>
    <% end %>
  </div>
</div>

<%= pagination_links @conn, @blocks %>

lib/helheim_web/templates/block/new.html.eex
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link gettext("Blocks & Ignores"), to: block_and_ignore_path(@conn, :index) %></li>
  <li class="breadcrumb-item active"><%= gettext "Create block" %></li>
</ol>

<div class="card">
  <div class="card-header">
    <%= gettext "Create block" %>
  </div>
  <%= render "form.html", conn: @conn, users: @users,
                          action: block_path(@conn, :create) %>
</div>

lib/helheim_web/templates/block/show.html.eex
<ol class="breadcrumb">
  <li class="breadcrumb-item active"><%= gettext("Blocked") %></li>
</ol>

<div class="text-center mb-2">
  <%= img_tag(static_path(@conn, "/images/block_owl.png"), class: "img-fluid") %>
  <hr class="mt-0">
  <h1><%= gettext "You have been blocked by %{username}!", username: @blocker.username %></h1>
  <p><%= gettext "While the block is active you will not be able to see or contact this user" %></p>

  <%= if Helheim.Block.blocked?(current_resource(@conn), @blocker) do %>
    <strong class="text-danger"><%= gettext "You are also blocking %{username}", username: @blocker.username %>!</strong>
  <% else %>
    <p class="mb-0 mt-1">
      <%= link to: block_path(@conn, :create, blockee_id: @blocker), class: "btn btn-default btn-block", method: "POST" do %>
        <i class="fa fa-lock"></i>
        <%= gettext "Click here to also block %{username}", username: @blocker.username %>
      <% end %>
    </p>
  <% end %>
</div>