lib/helheim_web/router.ex
defmodule HelheimWeb.Router do
  use HelheimWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HelheimWeb.Locale
  end

  pipeline :auth do
    plug HelheimWeb.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug HelheimWeb.Plug.TrackLogin
    plug HelheimWeb.Plug.LoadNotifications
    plug HelheimWeb.Plug.LoadUnreadPrivateConversations
    plug HelheimWeb.Plug.LoadPendingFriendships
    plug HelheimWeb.Plug.EnforceBan
    plug HelheimWeb.Plug.LoadPendingCalendarEvents
    plug HelheimWeb.Plug.LoadIgnorees
  end

  pipeline :ensure_admin do
    plug HelheimWeb.Plug.VerifyAdmin
  end

  pipeline :ensure_mod do
    plug HelheimWeb.Plug.VerifyMod
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser] # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/confirmation_pending", PageController, :confirmation_pending
    get "/debug", PageController, :debug
    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/confirmations", ConfirmationController, only: [:new, :create, :show]
    resources "/password_resets", PasswordResetController, only: [:new, :create, :show, :update]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/banned", PageController, :banned
    get "/help/verification", HelpController, :verification
    get "/signed_in", PageController, :signed_in
    get "/front_page", PageController, :front_page
    get "/staff", PageController, :staff
    get "/sessions/sign_out", SessionController, :delete
    resources "/account", AccountController, singleton: true, only: [:edit, :update, :delete]
    resources "/preferences", PreferenceController, singleton: true, only: [:edit, :update]
    resources "/profile", ProfileController, singleton: true, only: [:show, :edit, :update]
    resources "/profiles", ProfileController, only: [:index, :show], as: :public_profile do
      resources "/blog_posts", BlogPostController, only: [:index, :show] do
        resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      end
      resources "/comments", CommentController, only: [:index, :create, :edit, :update]
      resources "/photo_albums", PhotoAlbumController, only: [:index, :show] do
        resources "/photos", PhotoController, only: [:show] do
          resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
        end
        resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      end
      resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
      resources "/contact_request", FriendshipRequestController, singleton: true, only: [:create, :delete]
      resources "/contact", FriendshipController, singleton: true, only: [:create, :delete]
      resources "/contacts", FriendshipController, only: [:index]
    end
    resources "/blog_posts", BlogPostController, only: [:index, :new, :create, :edit, :update, :delete] do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/photo_albums", PhotoAlbumController, only: [:new, :create, :edit, :update, :delete] do
      resources "/photos", PhotoController, only: [:create, :edit, :update, :delete] do
        resources "/comments", CommentController, only: [:create, :edit, :update]
        resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
      end
      resources "/photo_positions", PhotoPositionController, singleton: true, only: [:update], as: :photo_positions
    end
    resources "/photos", PhotoController, only: [:index]
    resources "/private_conversations", PrivateConversationController, param: "partner_id", only: [:index, :show, :delete] do
      resources "/messages", PrivateMessageController, only: [:create], as: :message
    end
    resources "/forums", ForumController, only: [:index, :show] do
      resources "/forum_topics", ForumTopicController, only: [:new, :create, :show, :edit, :update] do
        resources "/forum_replies", ForumReplyController, only: [:create, :edit, :update]
      end
    end
    resources "/forum_topics", ForumTopicController, only: [] do
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/notifications", NotificationController, only: [:show]
    resources "/navbar", NavbarController, singleton: true, only: [:show]
    resources "/usernames", UsernameController, only: [:index, :show]
    resources "/blocks_and_ignores", BlockAndIgnoreController, only: [:index]
    resources "/blocks", BlockController, except: [:index]
    resources "/ignores", IgnoreController, except: [:index, :show]
    resources "/comments", CommentController, only: [:delete]
    resources "/donations", DonationController, only: [:new, :create]
    get "/donations/thank_you", DonationController, :thank_you
    resources "/contacts", FriendshipController, only: [:index]
    resources "/calendar_events", CalendarEventController do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/online_users", OnlineUserController, only: [:index]
  end

  scope "/mod", HelheimWeb.Mod, as: :mod do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_mod]

    resources "/calendar_events", CalendarEventController, only: [:index, :show, :update, :delete]
  end

  scope "/admin", HelheimWeb.Admin, as: :admin do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_admin]

    live_dashboard "/dashboard", metrics: HelheimWeb.Telemetry

    resources "/forum_categories", ForumCategoryController, only: [:index, :new, :create, :edit, :update, :delete] do
      resources "/forums", ForumController, only: [:new, :create, :edit, :update, :delete]
    end
    resources "/terms", TermController
    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      resources "/verification", User.VerificationController, singleton: true, only: [:create, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Helheim do
  #   pipe_through :api
  # end

  if Application.fetch_env!(:helheim, :env) == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/helheim_web/controllers/profile_controller.ex
defmodule HelheimWeb.ProfileController do
  use HelheimWeb, :controller
  alias Helheim.User
  alias Helheim.BlogPost
  alias Helheim.Comment
  alias Helheim.Photo
  alias Helheim.ForumTopic

  plug :scrub_get_params when action in [:index]
  plug :find_user when action in [:show]
  plug HelheimWeb.Plug.EnforceBlock when action in [:show]

  def index(conn, params) do
    search  = params["search"] || %{}
    sorting = search["sorting"] || "creation"
    users = User
            |> User.confirmed
            |> User.not_banned
            |> User.search(search)
            |> User.sort(sorting)
            |> Repo.paginate(page: sanitized_page(params["page"]))
    render(conn, "index.html", users: users)
  end

  def show(conn, params) do
    user = conn.assigns[:user]
    banned = if User.mod_or_admin?(Guardian.Plug.current_resource(conn)) && params["force"], do: false, else: User.banned?(user)
    render_profile(conn, user, banned)
  end

  defp render_profile(conn, user, true), do: render(conn, "show_banned.html", user: user)
  defp render_profile(conn, user, false) do
    newest_blog_posts =
      assoc(user, :blog_posts)
      |> BlogPost.published
      |> BlogPost.newest
      |> BlogPost.visible_by(current_resource(conn))
      |> BlogPost.not_private
      |> limit(4)
      |> Helheim.Repo.all
      |> Repo.preload(:user)
    newest_comments =
      assoc(user, :comments)
      |> Comment.not_deleted
      |> Comment.newest
      |> limit(5)
      |> Comment.with_preloads
      |> Helheim.Repo.all
    newest_forum_topics = ForumTopic
      |> where(user_id: ^user.id)
      |> ForumTopic.with_latest_reply
      |> order_by([desc: :updated_at])
      |> preload([:forum, :user])
      |> limit(6)
      |> Repo.all
    newest_photos = Photo
      |> Photo.by(user)
      |> Photo.newest
      |> Photo.visible_by(current_resource(conn))
      |> Photo.not_private
      |> limit(10)
      |> Repo.all
      |> Repo.preload(:photo_album)

    Helheim.VisitorLogEntry.track! current_resource(conn), user

    render conn, "show.html",
      user: user,
      newest_blog_posts: newest_blog_posts,
      newest_comments: newest_comments,
      newest_photos: newest_photos,
      newest_forum_topics: newest_forum_topics
  end

  def edit(conn, _params) do
    user = Guardian.Plug.current_resource(conn)
    changeset = User.profile_changeset(user)
    render conn, "edit.html", changeset: changeset
  end

  def update(conn, %{"user" => user_params}) do
    user = Guardian.Plug.current_resource(conn)
    changeset = User.profile_changeset(user, user_params)
    case Repo.update(changeset) do
      {:ok, _user} ->
        conn
        |> put_flash(:success, gettext("Profile updated!"))
        |> redirect(to: public_profile_path(conn, :show, user))
      {:error, changeset} ->
        conn
        |> render("edit.html", changeset: changeset)
    end
  end

  defp find_user(conn, _) do
    user = if conn.params["id"] do
      Repo.get!(User, conn.params["id"])
    else
      Guardian.Plug.current_resource(conn)
    end

    assign conn, :user, user
  end
end

lib/helheim_web/views/profile_view.ex
defmodule HelheimWeb.ProfileView do
  use HelheimWeb, :view
  alias Helheim.User
  alias Helheim.Block
  alias Helheim.Friendship
  alias HelheimWeb.FriendshipView
end

lib/helheim_web/templates/profile/cards.html.eex
<div class="card-group card-group-photos">
  <%= for user <- @users do %>
    <div class="card">
      <%= link to: public_profile_path(@conn, :show, user) do %>
        <%= img_tag(HelheimWeb.Avatar.url({user.avatar, user}, :thumb), class: "card-img-top img-fluid img-photo") %>
      <% end %>
      <div class="card-block">
        <p class="card-text mb-1">
          <strong><%= user.username %></strong><br>
          <small class="font-italic"><%= user.location || "..." %></small>
        </p>
        <div class="d-flex justify-content-between">
          <small><%= gettext "Created" %>:</small>
          <small><%= time_ago_in_words user.inserted_at %></small>
        </div>
        <div class="d-flex justify-content-between">
          <small><%= gettext "Login" %>:</small>
          <small><%= time_ago_in_words(user.last_login_at || user.inserted_at) %></small>
        </div>
      </div>
    </div>
  <% end %>
</div>

lib/helheim_web/templates/profile/details.html.eex
<table class="table table-sm">
  <tbody>
    <%= if Helheim.Donation.recently_donated?(@user) do %>
      <tr>
        <th colspan="2" class="text-center text-success">
          <%= link to: donation_path(@conn, :new), class: "" do %>
            <%= img_tag static_path(@conn, "/images/donor_icon.png"), class: "donor-icon mr-1" %>
            <%= gettext "Has recently supported Helheim" %>
            <%= img_tag static_path(@conn, "/images/donor_icon.png"), class: "donor-icon ml-1" %>
          <% end %>
        </th>
      </tr>
    <% end %>

    <tr>
      <th><%= gettext "Joined" %>:</th>
      <td><%= time_ago_in_words @user.inserted_at %></td>
    </tr>

    <tr>
      <th><%= gettext "Last login" %>:</th>
      <td><%= time_ago_in_words(@user.last_login_at || @user.inserted_at) %></td>
    </tr>

    <%= if @user.gender do %>
      <tr>
        <th><%= gettext "Gender" %>:</th>
        <td><%= @user.gender %></td>
      </tr>
    <% end %>

    <%= if @user.birthday do %>
      <tr>
        <th><%= gettext "Age" %>:</th>
        <td><%= User.age @user, Timex.now %></td>
      </tr>
    <% end %>

    <%= if not is_nil(@user.unicorn_at) do %>
      <tr>
        <th><%= gettext "Partner status" %>:</th>
        <td class="mentionable">
          Har sværget evigt troskab til
          <img src="<%= HelheimWeb.Router.Helpers.static_url(HelheimWeb.Endpoint, "/images/unicorn_avatar.gif") %>" class="img-avatar" height="32" alt="rainbow_unicorn">
          @rainbow_unicorn
          <img src="<%= HelheimWeb.Router.Helpers.static_url(HelheimWeb.Endpoint, "/images/unicorn_avatar.gif") %>" class="img-avatar" height="32" alt="rainbow_unicorn">
        </td>
      </tr>
    <% end %>
    <%= if is_nil(@user.unicorn_at) and @user.partnership_status do %>
      <tr>
        <th><%= gettext "Partner status" %>:</th>
        <td class="mentionable"><%= @user.partnership_status %></td>
      </tr>
    <% end %>

    <%= if @user.location do %>
      <tr>
        <th><%= gettext "Location" %>:</th>
        <td><%= @user.location %></td>
      </tr>
    <% end %>

    <tr>
      <th><%= gettext "Contacts" %>:</th>
      <td>
        <%= link to: public_profile_friendship_path(@conn, :index, @user) do %>
          <%= Friendship.count(@user) %>
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

lib/helheim_web/templates/profile/edit.html.eex
<div class="row">
  <div class="col-md-12">
    <%= form_for @changeset, profile_path(@conn, :update), [multipart: true], fn f -> %>
      <div class="card">
        <div class="card-header">
          <strong><%= gettext "Profile Settings" %></strong>
        </div>
        <div class="card-block p-2">
          <div class="row">
            <div class="col-lg-4 col-sm-12 mb-1">
              <h5 class="mb-1"><%= gettext "Profile Photo" %></h5>
              <hr>
              <div class="img-thumbnail img-thumbnail-with-form-control">
                <img src="<%= HelheimWeb.Avatar.url({@changeset.data.avatar, @changeset.data}, :large) %>" class="img-fluid mx-auto d-block" alt="<%= gettext "Profile Photo" %>">
                <%= file_input f, :avatar, class: "form-control" %>
              </div>

              <%= if message = f.errors[:avatar] do %>
                <div class="form-control-feedback"><%= translate_error(message) %></div>
              <% else %>
                <small>
                  <%= gettext "Maximum file size: %{file_size}", file_size: HelheimWeb.Avatar.max_file_size |> Crutches.Format.Number.as_human_size %><br>
                  <%= gettext "Submit your changes to upload the image" %>
                </small>
              <% end %>
            </div>

            <div class="col-lg-8 col-sm-12 mb-1">
              <h5 class="mb-1"><%= gettext "Basic Details" %></h5>
              <hr>
              <div class="form-group">
                <%= label f, :gender, gettext("Gender") %>
                <%=
                  select f,
                         :gender,
                         [{gettext("Not specified"), ""}, gettext("Male"), gettext("Female")],
                         class: "form-control",
                         "data-custom-label": gettext("Custom"),
                         "data-custom-input": "#user_gender_custom",
                         "data-custom-value": @changeset.data.gender || ""
                %>
                <%= text_input f, :gender_custom, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= label f, :location, gettext("Location") %>
                <%= text_input f, :location, class: "form-control" %>
              </div>

              <div class="form-group">
                <%= label f, :partnership_status, gettext("Partner status") %>
                <%=
                  select f,
                         :partnership_status,
                         [
                           {gettext("Not specified"), ""}, gettext("Single"), gettext("In a relationship"), gettext("Married"),
                           gettext("In an open relationship"), gettext("None of your business")
                         ],
                         class: "form-control",
                         "data-custom-label": gettext("Custom"),
                         "data-custom-input": "#user_partnership_status_custom",
                         "data-custom-value": @changeset.data.partnership_status || ""
                %>
                <%= text_input f, :partnership_status_custom, class: "form-control mentionable-input" %>
              </div>

              <div class="form-group">
                <%= label f, :birthday, gettext("Birthday") %><br>
                <%= date_select f, :birthday, builder: fn b -> %>
                  <%= b.(:day, prompt: "", class: "custom-select") %> /
                  <%= b.(:month, options: gettext_month_options(),prompt: "", class: "custom-select") %> /
                  <%= b.(:year, options: Timex.now.year..(Timex.now.year - 100), prompt: "", class: "custom-select") %>
                <% end %>
                <small class="form-text">
                  <i class="fa fa-info fa-fw"></i>
                  <%= gettext "We never show your birthday directly to other users, only your age, although some users might be able to guess it by observing your age increasing..." %>
                </small>
              </div>

              <h5 class="mb-1"><%= gettext "Profile Text" %></h5>
              <hr>
              <div class="form-group <%= if f.errors[:profile_text] do 'has-danger' end %>">
                <%= label f, :profile_text, gettext("Content"), class: "control-label" %>
                <%= hidden_input f, :profile_text %>
                <div id="profile_text_editor"></div>
                <%= if message = f.errors[:profile_text] do %>
                  <div class="form-control-feedback"><%= translate_error(message) %></div>
                <% end %>
              </div>
              <p>
                <i class="fa fa-info fa-fw"></i>
                <%= gettext "Hint" %>: <%= gettext "You can embed pictures from your photo albums or from Imgur, gifs from Giphy, Videos from Youtube and Vimeo and Spotify playlists by simply including a url for the desired media in your post" %>
              </p>
            </div>
          </div>
        </div>
        <div class="card-footer">
          <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> <%= gettext "Update Profile" %></button>
        </div>
      </div>
    <% end %>
  </div>
</div>

lib/helheim_web/templates/profile/index.html.eex
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= gettext "Profiles" %></li>
</ol>

<div class="card" id="search-outer">
  <div class="card-header">
    <a data-toggle="collapse" data-parent="#search-outer" href="#search-body">
      <%= gettext "Search" %>
    </a>
  </div>
  <div id="search-body" class="collapse hide">
    <div class="card-block">
      <%= form_for @conn, public_profile_path(@conn, :index), [as: :search, method: :get], fn f -> %>
        <div class="form-group">
          <%= label f, :username, gettext("Username") %>
          <%= text_input f, :username, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label f, :location, gettext("Location") %>
          <%= text_input f, :location, class: "form-control" %>
        </div>

        <div class="form-group">
          <%= label f, :sorting, gettext("Sorting") %>
          <%= select f, :sorting, [
            [key: gettext("Sort by creation"), value: "creation"],
            [key: gettext("Sort by login"), value: "login"]],
            class: "form-control" %>
        </div>

        <%= submit gettext("Search"), class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

<%= render "cards.html", conn: @conn, users: @users.entries %>

<%= pagination_links @conn, @users, %{search: @conn.params["search"]} %>

lib/helheim_web/templates/profile/show.html.eex
<div class="row mt-1">
  <div class="col-xl-5 col-lg-6">
    <div class="card">
      <div class="card-block">
        <img
          src="<%= HelheimWeb.Avatar.url({@user.avatar, @user}, :large) %>"
          class="rounded img-fluid mx-auto d-block mb-1"
          alt="<%= @user.username %>"
        >
        <h1><%= username @user %></h1>
        <p class="mb-1">
          <%= visitor_count_badge @conn, @user %>
          <%= if User.verified?(@user) do %>
            <%= link to: help_path(@conn, :verification), class: "badge badge-success" do %>
              <i class="fa fa-fw fa-check-circle"></i>
              <%= gettext "Verified user" %>
            <% end %>
          <% end %>
        </p>

        <%= render "details.html", conn: @conn, user: @user %>

        <%= if @user.id != current_resource(@conn).id do %>
          <p class="mb-0 mt-1">
            <%= link to: private_conversation_path(@conn, :show, @user.id), class: "btn btn-primary btn-block" do %>
              <i class="fa fa-envelope"></i>
              <%= gettext "Send private message" %>
            <% end %>
          </p>

          <p class="mb-0 mt-1">
            <%= render FriendshipView,
                       "_friend_request_button_#{Friendship.status(current_resource(@conn), @user)}.html",
                       conn: @conn,
                       user: @user %>
          </p>

          <%= if Block.blocked?(current_resource(@conn), @user) do %>
            <div class="alert alert-warning mt-1" role="alert">
              <strong><%= gettext "This user is blocked" %>!</strong>
              <%= gettext "The user will be unable to see your profile, blog posts, photos or send you messages while blocked" %>.
              <p class="mb-0 mt-1">
                <%= link to: block_path(@conn, :delete, @user.id), class: "btn btn-default btn-block", method: "DELETE" do %>
                  <i class="fa fa-unlock"></i>
                  <%= gettext "Unblock user" %>
                <% end %>
              </p>
            </div>
          <% else %>
            <p class="mb-0 mt-1">
              <%= link to: block_path(@conn, :create, blockee_id: @user.id), class: "btn btn-default btn-block", method: "POST" do %>
                <i class="fa fa-lock"></i>
                <%= gettext "Block user" %>
              <% end %>
            </p>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="col-xl-7 col-lg-6 embeds mentionable">
    <%= if User.banned?(@user) do %>
      <div class="alert alert-danger" role="alert">
        <%= gettext("This user is banned") %>
      </div>
    <% end %>

    <%= HelheimWeb.EmbedHelpers.raw_replace_urls(@user.profile_text) %>
  </div>
</div>

<div class="card-group">
  <div class="card">
    <div class="card-block">
      <h5 class="mb-1"><%= gettext "Newest Blogs" %></h5>
      <%= for blog_post <- @newest_blog_posts do %>
        <%= render HelheimWeb.BlogPostView, "list_entry.html", conn: @conn, blog_post: blog_post %>
      <% end %>

      <%= link gettext("Show All"), to: public_profile_blog_post_path(@conn, :index, @user), class: "btn btn-outline-secondary btn-block mb-0" %>
    </div>
  </div>

  <div class="card">
    <div class="card-block">
      <h5 class="mb-1"><%= gettext "Newest Forum Posts" %></h5>
      <div class="list-group">
        <%= for forum_topic <- @newest_forum_topics do %>
          <%= render HelheimWeb.ForumView, "forum_topic.html", conn: @conn, forum_topic: forum_topic %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="card">
  <div class="card-block">
    <h5 class="mb-1"><%= gettext "Newest Photos" %></h5>
    <div class="card-group card-group-photos">
      <%= for photo <- @newest_photos do %>
        <%= render HelheimWeb.PhotoView, "thumb.html", conn: @conn, user: @user, photo: photo %>
      <% end %>
    </div>
    <%= link gettext("Show All"), to: public_profile_photo_album_path(@conn, :index, @user), class: "btn btn-outline-secondary btn-block mb-0" %>
  </div>
</div>

<%= HelheimWeb.CommentView.render_comments @conn, @newest_comments, @user, limited: true %>

lib/helheim_web/templates/profile/show_banned.html.eex
<div class="text-center mb-2 mt-2">
  <%= img_tag(static_path(@conn, "/images/block_owl.png"), class: "img-fluid") %>
  <hr>
  <h1><%= gettext("This user is banned") %></h1>
  <%= if User.mod_or_admin?(current_resource(@conn)) do %>
    <%= link gettext("Mod: Show profile"), to: public_profile_path(@conn, :show, @user, force: "true") %>
  <% end %>
</div>

lib/helheim_web/templates/profile/show_unicorn.html.eex
<div class="row mt-1">
  <div class="col-xl-5 col-lg-6">
    <div class="card">
      <div class="card-block">
        <img
          src="<%= HelheimWeb.Avatar.url_with_unicorn({@user.avatar, @user}, :large, Guardian.Plug.current_resource(@conn)) %>"
          class="rounded img-fluid mx-auto d-block mb-1"
          alt="<%= @user.username %>"
        >
        <h1>
          <span style="color: #ec5cc6">r</span>
          <span style="color: #bcffbb">a</span>
          <span style="color: #1bb2da">i</span>
          <span style="color: #c485ff">n</span>
          <span style="color: #fefd9e">b</span>
          <span style="color: #ffcc55">o</span>
          <span style="color: #ec5cc6">w</span>
          <span style="color: #bcffbb">_</span>
          <span style="color: #1bb2da">u</span>
          <span style="color: #c485ff">n</span>
          <span style="color: #fefd9e">i</span>
          <span style="color: #ffcc55">c</span>
          <span style="color: #ec5cc6">o</span>
          <span style="color: #bcffbb">r</span>
          <span style="color: #1bb2da">n</span>
        </h1>
        <p class="mb-1">
          <%= visitor_count_badge @conn, @user %>
        </p>

        <%= render "details.html", conn: @conn, user: @user %>
      </div>
    </div>
  </div>

  <div class="col-xl-7 col-lg-6 embeds mentionable">
    <div class="embed-responsive embed-responsive-16by9 embed-unicorn">
      <iframe src="https://www.youtube-nocookie.com/embed/5wb5HWVh6Fs?rel=0&controls=0&autoplay=1&showinfo=0&modestbranding=1" frameborder="0" allow="autoplay; encrypted-media;" allowfullscreen></iframe>
    </div>
  </div>
</div>

<%= HelheimWeb.CommentView.render_comments @conn, @newest_comments, @user, limited: true %>