lib/helheim_web/router.ex
defmodule HelheimWeb.Router do
  use HelheimWeb, :router
  use Plug.ErrorHandler
  use Sentry.Plug

  import Phoenix.LiveDashboard.Router

  pipeline :browser do
    plug :accepts, ["html", "json"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug HelheimWeb.Locale
  end

  pipeline :auth do
    plug HelheimWeb.Auth.Pipeline
  end

  pipeline :ensure_auth do
    plug Guardian.Plug.EnsureAuthenticated
    plug HelheimWeb.Plug.TrackLogin
    plug HelheimWeb.Plug.LoadNotifications
    plug HelheimWeb.Plug.LoadUnreadPrivateConversations
    plug HelheimWeb.Plug.LoadPendingFriendships
    plug HelheimWeb.Plug.EnforceBan
    plug HelheimWeb.Plug.LoadPendingCalendarEvents
    plug HelheimWeb.Plug.LoadIgnorees
  end

  pipeline :ensure_admin do
    plug HelheimWeb.Plug.VerifyAdmin
  end

  pipeline :ensure_mod do
    plug HelheimWeb.Plug.VerifyMod
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser] # Use the default browser stack

    resources "/sessions", SessionController, only: [:new, :create]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser, :auth] # Use the default browser stack

    get "/", PageController, :index
    get "/terms", PageController, :terms
    get "/confirmation_pending", PageController, :confirmation_pending
    get "/debug", PageController, :debug
    resources "/registrations", RegistrationController, only: [:new, :create]
    resources "/confirmations", ConfirmationController, only: [:new, :create, :show]
    resources "/password_resets", PasswordResetController, only: [:new, :create, :show, :update]
  end

  scope "/", HelheimWeb do
    pipe_through [:browser, :auth, :ensure_auth]

    get "/banned", PageController, :banned
    get "/help/verification", HelpController, :verification
    get "/signed_in", PageController, :signed_in
    get "/front_page", PageController, :front_page
    get "/staff", PageController, :staff
    get "/sessions/sign_out", SessionController, :delete
    resources "/account", AccountController, singleton: true, only: [:edit, :update, :delete]
    resources "/preferences", PreferenceController, singleton: true, only: [:edit, :update]
    resources "/profile", ProfileController, singleton: true, only: [:show, :edit, :update]
    resources "/profiles", ProfileController, only: [:index, :show], as: :public_profile do
      resources "/blog_posts", BlogPostController, only: [:index, :show] do
        resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      end
      resources "/comments", CommentController, only: [:index, :create, :edit, :update]
      resources "/photo_albums", PhotoAlbumController, only: [:index, :show] do
        resources "/photos", PhotoController, only: [:show] do
          resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
        end
        resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      end
      resources "/visitor_log_entries", VisitorLogEntryController, only: [:index]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
      resources "/contact_request", FriendshipRequestController, singleton: true, only: [:create, :delete]
      resources "/contact", FriendshipController, singleton: true, only: [:create, :delete]
      resources "/contacts", FriendshipController, only: [:index]
    end
    resources "/blog_posts", BlogPostController, only: [:index, :new, :create, :edit, :update, :delete] do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/photo_albums", PhotoAlbumController, only: [:new, :create, :edit, :update, :delete] do
      resources "/photos", PhotoController, only: [:create, :edit, :update, :delete] do
        resources "/comments", CommentController, only: [:create, :edit, :update]
        resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
      end
      resources "/photo_positions", PhotoPositionController, singleton: true, only: [:update], as: :photo_positions
    end
    resources "/photos", PhotoController, only: [:index]
    resources "/private_conversations", PrivateConversationController, param: "partner_id", only: [:index, :show, :delete] do
      resources "/messages", PrivateMessageController, only: [:create], as: :message
    end
    resources "/forums", ForumController, only: [:index, :show] do
      resources "/forum_topics", ForumTopicController, only: [:new, :create, :show, :edit, :update] do
        resources "/forum_replies", ForumReplyController, only: [:create, :edit, :update]
      end
    end
    resources "/forum_topics", ForumTopicController, only: [] do
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/notifications", NotificationController, only: [:show]
    resources "/navbar", NavbarController, singleton: true, only: [:show]
    resources "/usernames", UsernameController, only: [:index, :show]
    resources "/blocks_and_ignores", BlockAndIgnoreController, only: [:index]
    resources "/blocks", BlockController, except: [:index]
    resources "/ignores", IgnoreController, except: [:index, :show]
    resources "/comments", CommentController, only: [:delete]
    resources "/donations", DonationController, only: [:new, :create]
    get "/donations/thank_you", DonationController, :thank_you
    resources "/contacts", FriendshipController, only: [:index]
    resources "/calendar_events", CalendarEventController do
      resources "/comments", CommentController, only: [:create, :edit, :update]
      resources "/notification_subscription", NotificationSubscriptionController, singleton: true, only: [:update]
    end
    resources "/online_users", OnlineUserController, only: [:index]
  end

  scope "/mod", HelheimWeb.Mod, as: :mod do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_mod]

    resources "/calendar_events", CalendarEventController, only: [:index, :show, :update, :delete]
  end

  scope "/admin", HelheimWeb.Admin, as: :admin do
    pipe_through [:browser, :auth, :ensure_auth, :ensure_admin]

    live_dashboard "/dashboard", metrics: HelheimWeb.Telemetry

    resources "/forum_categories", ForumCategoryController, only: [:index, :new, :create, :edit, :update, :delete] do
      resources "/forums", ForumController, only: [:new, :create, :edit, :update, :delete]
    end
    resources "/terms", TermController
    resources "/users", UserController, only: [:index, :show, :edit, :update] do
      resources "/verification", User.VerificationController, singleton: true, only: [:create, :delete]
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", Helheim do
  #   pipe_through :api
  # end

  if Application.fetch_env!(:helheim, :env) == :dev do
    forward "/sent_emails", Bamboo.SentEmailViewerPlug
  end
end

lib/helheim/models/photo_album.ex
defmodule Helheim.PhotoAlbum do
  use Helheim, :model

  alias Helheim.Repo
  alias Helheim.Photo

  schema "photo_albums" do
    field :title,         :string
    field :description,   :string
    field :visibility,    :string
    field :visitor_count, :integer
    field :comment_count, :integer

    timestamps(type: :utc_datetime_usec)

    belongs_to :user,                Helheim.User
    has_many   :photos,              Helheim.Photo
    has_many   :visitor_log_entries, Helheim.VisitorLogEntry
    has_many   :comments,            Helheim.Comment
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:title, :description, :visibility])
    |> trim_fields([:title, :description])
    |> validate_required([:title, :visibility])
    |> validate_inclusion(:visibility, Helheim.Visibility.visibilities)
  end

  def alphabetical(query) do
    from pa in query,
    order_by: [desc: pa.title]
  end

  def visible_by(query, user) do
    verified = Helheim.User.verified?(user)

    from pa in query,
    where: pa.visibility == "public" or pa.user_id == ^user.id or (pa.visibility == "verified_only" and ^verified) or (
      (pa.visibility == "friends_only" or pa.visibility == "verified_only") and fragment(
        "EXISTS(?)",
        fragment(
          "
            SELECT 1 FROM friendships
            WHERE
              friendships.accepted_at IS NOT NULL AND
              friendships.sender_id IN (?,?) AND
              friendships.recipient_id IN (?,?)
          ", pa.user_id, ^user.id, pa.user_id, ^user.id
        )
      )
    )
  end

  def reposition_photos!(photo_album, photo_ids) do
    from(
      p in Photo,
      where: p.photo_album_id == ^photo_album.id,
      update: [set: [position: fragment("array_position(?, id) - 1", ^photo_ids)]]
    ) |> Repo.update_all([])
  end

  def delete!(photo_album) do
    photos = assoc(photo_album, :photos) |> Repo.all
    Parallel.pmap(photos, fn(p) -> Helheim.Photo.delete!(p) end)
    Repo.delete!(photo_album)
  end
end

lib/helheim_web/controllers/photo_album_controller.ex
defmodule HelheimWeb.PhotoAlbumController do
  use HelheimWeb, :controller
  alias Helheim.User
  alias Helheim.PhotoAlbum
  alias Helheim.Photo

  plug :find_user when action in [:index, :show]
  plug HelheimWeb.Plug.EnforceBlock when action in [:index, :show]

  def index(conn, params = %{"profile_id" => _}) do
    user = conn.assigns[:user]
    photos_query = from p in Photo, order_by: p.position, distinct: p.photo_album_id
    photo_albums =
      assoc(user, :photo_albums)
      |> PhotoAlbum.visible_by(current_resource(conn))
      |> preload([photos: ^photos_query])
      |> Repo.paginate(page: sanitized_page(params["page"]))
    render(conn, "index.html", user: user, photo_albums: photo_albums)
  end

  def new(conn, _params) do
    user = current_resource(conn)
    changeset =
      user
        |> Ecto.build_assoc(:photo_albums)
        |> PhotoAlbum.changeset(%{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"photo_album" => photo_album_params}) do
    user = current_resource(conn)
    changeset =
      user
        |> Ecto.build_assoc(:photo_albums)
        |> PhotoAlbum.changeset(photo_album_params)

    case Repo.insert(changeset) do
      {:ok, photo_album} ->
        conn
        |> put_flash(:success, gettext("Photo album created successfully."))
        |> redirect(to: public_profile_photo_album_path(conn, :show, user, photo_album))
      {:error, changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"profile_id" => _, "id" => id}) do
    user = conn.assigns[:user]
    photo_album =
      assoc(user, :photo_albums)
      |> PhotoAlbum.visible_by(current_resource(conn))
      |> Repo.get!(id)
    photos =
      assoc(photo_album, :photos)
      |> Photo.in_positional_order
      |> preload(:photo_album)
      |> Repo.all
    Helheim.VisitorLogEntry.track! current_resource(conn), photo_album
    render(conn, "show.html", user: user, photo_album: photo_album, photos: photos)
  end

  def edit(conn, %{"id" => id}) do
    user = current_resource(conn)
    photo_album = assoc(user, :photo_albums) |> Repo.get!(id)
    changeset = PhotoAlbum.changeset(photo_album)
    render(conn, "edit.html", photo_album: photo_album, changeset: changeset)
  end

  def update(conn, %{"id" => id, "photo_album" => photo_album_params}) do
    user = current_resource(conn)
    photo_album = assoc(user, :photo_albums) |> Repo.get!(id)
    changeset = PhotoAlbum.changeset(photo_album, photo_album_params)

    case Repo.update(changeset) do
      {:ok, photo_album} ->
        conn
        |> put_flash(:success, gettext("Photo album updated successfully."))
        |> redirect(to: public_profile_photo_album_path(conn, :show, user, photo_album))
      {:error, changeset} ->
        render(conn, "edit.html", photo_album: photo_album, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user        = current_resource(conn)
    photo_album = assoc(user, :photo_albums) |> Repo.get!(id)

    PhotoAlbum.delete!(photo_album)

    conn
    |> put_flash(:success, gettext("Photo Album deleted successfully."))
    |> redirect(to: public_profile_photo_album_path(conn, :index, user))
  end

  defp find_user(conn, _) do
    assign_user(conn, conn.params)
  end

  defp assign_user(conn, %{"profile_id" => profile_id}) do
    conn
    |> assign(:user, Repo.get!(User, profile_id))
  end
  defp assign_user(conn, _), do: conn
end

lib/helheim_web/views/photo_album_view.ex
defmodule HelheimWeb.PhotoAlbumView do
  use HelheimWeb, :view
end

lib/helheim_web/templates/photo_album/edit.html.eex
<div class="card">
  <div class="card-header">
    <%= gettext "Edit Photo Album" %>
  </div>
  <%= render "form.html", changeset: @changeset,
                          action: photo_album_path(@conn, :update, @photo_album) %>
</div>

lib/helheim_web/templates/photo_album/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <div class="card-block">
    <div class="form-group <%= if f.errors[:title] do 'has-danger' end %>">
      <%= label f, :title, gettext("Title"), class: "control-label" %>
      <%= text_input f, :title, class: "form-control" %>
      <%= if message = f.errors[:title] do %>
        <div class="form-control-feedback"><%= translate_error(message) %></div>
      <% end %>
    </div>

    <div class="form-group <%= if f.errors[:description] do 'has-danger' end %>">
      <%= label f, :description, gettext("Description"), class: "control-label" %>
      <%= textarea f, :description, class: "form-control", rows: 10 %>
      <%= if message = f.errors[:description] do %>
        <div class="form-control-feedback"><%= translate_error(message) %></div>
      <% end %>
    </div>

    <div class="form-group <%= if f.errors[:visibility] do 'has-danger' end %>">
      <%= label f, :visibility, gettext("Visibility"), class: "control-label" %>
      <%= select f, :visibility, Helheim.Visibility.visibilities_with_human, class: "form-control" %>
      <%= if message = f.errors[:visibility] do %>
        <div class="form-control-feedback"><%= translate_error(message) %></div>
      <% end %>
    </div>
  </div>
  <div class="card-footer">
    <button type="submit" class="btn btn-sm btn-primary"><i class="fa fa-dot-circle-o"></i> <%= gettext "Save Photo Album" %></button>
  </div>
<% end %>

lib/helheim_web/templates/photo_album/index.html.eex
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= username @user, true %></li>
  <li class="breadcrumb-item active"><%= gettext "Photo Albums" %></li>
</ol>

<div class="card-group card-group-photos">
  <%= for photo_album <- @photo_albums.entries do %>
    <% photo = List.first photo_album.photos %>
    <div class="card">
        <%= link to: public_profile_photo_album_path(@conn, :show, @user, photo_album) do %>
          <%= if photo do %>
            <%= if photo.nsfw do %>
              <%= img_tag(static_path(@conn, "/images/photo_thumb_nsfw.jpg"), class: "card-img-top img-fluid") %>
            <% else %>
              <%= img_tag(HelheimWeb.PhotoFile.url({photo.file, photo}, :thumb), class: "card-img-top img-fluid") %>
            <% end %>
          <% else %>
            <%= img_tag(static_path(@conn, "/images/photo_thumb_default.jpg"), class: "card-img-top img-fluid") %>
          <% end %>
        <% end %>
      <div class="card-block">
        <p class="card-text">
          <strong class="text-break-up"><%= photo_album.title %></strong>
          <br>
          <%= if photo do %>
            <small><%= time_ago_in_words photo.inserted_at %></small>
          <% end %>
          <%= visitor_count_badge @conn, photo_album %>
        </p>
        <%= visibility_badge photo_album %>
      </div>
    </div>
  <% end %>
  <%= if me?(@conn, @user) do %>
    <div class="card">
      <div class="card-block text-center d-flex flex-column justify-content-center">
        <i class="fa fa-plus fa-5x mb-1"></i>
        <%= link gettext("Create New"), to: photo_album_path(@conn, :new), class: "btn btn-primary btn-block" %>
      </div>
    </div>
  <% end %>
</div>

<%= pagination_links @conn, @photo_albums %>

lib/helheim_web/templates/photo_album/new.html.eex
<div class="card">
  <div class="card-header">
    <%= gettext "New Photo Album" %>
  </div>
  <%= render "form.html", changeset: @changeset,
                          action: photo_album_path(@conn, :create) %>
</div>

lib/helheim_web/templates/photo_album/show.html.eex
<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= username @user, true %></li>
  <li class="breadcrumb-item"><%= link gettext("Photo Albums"), to: public_profile_photo_album_path(@conn, :index, @user) %></li>
  <li class="breadcrumb-item active"><%= @photo_album.title %></li>
</ol>

<blockquote class="blockquote text-left">
  <%= if @photo_album.description do %>
    <p><%= text_to_html @photo_album.description %></p>
  <% end %>
  <%= visibility_badge @photo_album %>
  <%= visitor_count_badge @conn, @photo_album %>
</blockquote>

<%= if @photo_album.user_id == current_resource(@conn).id do %>
  <div class="alert alert-info">
    <i class="fa fa-info-circle"></i>
    <strong><%= gettext "Did you know" %></strong>
    <%= gettext "that you can reorder your photos by dragging and dropping them!" %>
    <small><%= gettext "(only in desktop browsers)" %></small>
  </div>
<% end %>

<div class="card-group card-group-photos<%= if @photo_album.user_id == current_resource(@conn).id do " mine" end %>" id="photos" data-reposition-url="<%= photo_album_photo_positions_path(@conn, :update, @photo_album) %>">
  <%= for photo <- @photos do %>
    <%= render HelheimWeb.PhotoView, "thumb.html", conn: @conn, user: @user, photo_album: @photo_album, photo: photo %>
  <% end %>
</div>

<%= if me?(@conn, @user) do %>
  <div class="card">
    <div class="card-header">
      <%= gettext "Upload Photos" %>
    </div>
    <div class="card-block">
      <%= render "space_used.html", conn: @conn, user: @user %>

      <%= form_for @conn, photo_album_photo_path(@conn, :create, @photo_album), [as: :photo, multipart: true, id: "photo-dropzone", class: "dropzone"], fn f -> %>
        <div class="form-group">
          <span class="text-warning"><i class="fa fa-warning"></i></span>
          <%= label f, :nsfw, gettext("Please turn on this switch before uploading NSFW photos:"), class: "control-label" %>
          <%= label f, :nsfw, class: "switch switch-text switch-primary" do %>
            <%= checkbox f, :nsfw, class: "switch-input" %>
            <span class="switch-label" data-on="On" data-off="Off"></span>
            <span class="switch-handle"></span>
          <% end %>
        </div>
        <div class="dz-message">
          <%= gettext "Drop photos here (or click) to upload..." %>
        </div>
      <% end %>
    </div>
    <div class="card-footer">
      <%= link to: photo_album_path(@conn, :edit, @photo_album), class: "btn btn-sm btn-primary" do %>
        <i class="fa fa-pencil"></i>
        <%= gettext("Edit Photo Album") %>
      <% end %>

      <%= link to: photo_album_path(@conn, :delete, @photo_album), method: :delete, data: [confirm: gettext("Are you sure you want to delete this photo album? All photos in the album will be deleted with no way to recover them.")], class: "btn btn-danger btn-sm float-right" do %>
        <i class="fa fa-trash"></i>
        <%= gettext "Delete" %>
      <% end %>
    </div>
  </div>
<% end %>

lib/helheim_web/templates/photo_album/space_used.html.eex
<div id="photo-space-used">
  <%
    space_used = Helheim.Photo.total_used_space_by @user
    max_space  = current_resource(@conn).max_total_file_size
  %>
  <%= if space_used > 0 do %>
    <% percent_used = round(space_used / max_space * 100) %>
    <%=
      gettext "You have used %{used_space} out of a maximum of %{max_space} across all your photo albums", [
        used_space: Crutches.Format.Number.as_human_size(space_used),
        max_space: Crutches.Format.Number.as_human_size(max_space)
      ]
    %>
    <div class="progress mb-1">
      <div class="progress-bar" role="progressbar" style="width: <%= percent_used %>%;" aria-valuenow="<%= percent_used %>" aria-valuemin="0" aria-valuemax="100"><%= percent_used %>%</div>
    </div>
  <% end %>
</div>